services:
  # --- Gateway Service ---
  ngelmak-gateway:
    build: .
    container_name: ngelmak-gateway
    ports:
      - "4000:4000"
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true